ourjapanlife/findadoc-server

README.md
Adds a message to the README that we aren't accepting new contributors and also a link to our back-end channel on Slack for anyone that would like to make suggestions or leave feedback.
=> docs: update contributor info in readme

.gitignore
Resolves #55 
Better env management
Testing instructions:
try editing `env.sample` and ensure git sees the changes
=> better env management

.github/workflows/reviewdog.yml
Signed-off-by: Ann Kilzer キルザー杏 <akilzer@gmail.com>
=> tell the dog to "sit" on drafts, etc.

.github/ISSUE_TEMPLATE/default.md, .github/pull_request_template.md
=> Issue and PR templates

.eslintrc.json, .github/workflows/reviewdog.yml, prisma/seed.ts
Resolves #70 
Fix the linting challenges in CI/CD
edit a file with some typescript and hope the dog chills out
=> Fix CI/CD linting

src/resolvers.ts, src/services/healthcareProfessionalService.ts
Changes the property `acceptedInsuranceOptions` to `acceptedInsurance` to match the schema.
1. Changing the name back to `acceptedInsuranceOptions` should show the following error:
=> chore: change acceptedInsuranceOptions to acceptedInsurance

.eslintrc.js, prisma/devSetup.ts, prisma/loadCsv.ts, prisma/seed.ts, src/db/client.ts, src/index.ts, src/resolvers.ts, src/schema.ts, src/services/degreeService.ts, src/services/facilityService.ts, src/services/healthcareProfessionalService.ts, src/services/specialtyService.ts, src/services/spokenLanguageService.ts, src/tests/degreeQuery.ts, src/tests/healthcareProfessionalQuery.ts, src/typesgeneratorconfig.ts
Resolves #119 
- Semi-colons are off and will error in the linter
- Update files
Linter must pass
=> 119 Goodbye SemiColons

.github/CODEOWNERS
Resolves #162 
updating codeowners file
- removing ann
- adding in jacob
=> removing ann and adding in jacob for codeowners

src/database.ts, src/databaseSeedTool.ts, src/fakeData/facilities.ts, src/index.ts, src/resolvers.ts, src/services/facilityService.ts, src/services/healthcareProfessionalService.ts, src/typeDefs/dbSchema.ts
Resolves #180
- gql queries work now!
=> got build and queries working again!

renovate.json
Sets the confidence level to "high" or "very high" for mend renovate PRs.
=> chore: set renovate confidence to high

src/resolvers.ts, src/services/facilityService.ts, src/services/healthcareProfessionalService.ts, src/typeDefs/dbSchema.ts, src/typeDefs/schema.graphql
Resolves #219
1. `addFacility` now saves a healthcareProfessional to the `healthcareProfessionals` database collection, and then stores the id in an array to the new Facility in the `facilities` collection.
2. `addHealthcareProfessionalToFacility` was created as a separate function from `addHealthcareProfessional` to allow a HealthcareProfessional to be added to an existing Facility by passing the `facilityId`.
Operation: 
```
mutation CreateFacilityWithHealthcareProfessional($input: FacilityInput) {
createFacilityWithHealthcareProfessional(input: $input) {
id
}
}
```
Variables:
```
{
"input": {
"nameJa": "some facility name",
"nameEn": "some facility name",
"contact": {
"email": "email",
"address": {
"addressLine1En": "some address",
"addressLine1Ja": "some address",
"addressLine2En": …
```
=> Refactor FacilityService and HealthcareProfessionalService

.all-contributorsrc, README.md
Update contributors via CLI since the bot isn't working.
=> :busts_in_silhouette: Add @evan-desu as a contributor

src/resolvers.ts, src/services/submissionService.ts, src/typeDefs/dbSchema.ts, src/typeDefs/schema.graphql
Previously, there was no way to retrieve multiple submissions from the database. There is now a function that does this, and allows the user to search by any number of provided filters.
Resolves #212 
This PR is part of a 🥞:
1. https://github.com/ourjapanlife/findadoc-server/pull/213
2. https://github.com/ourjapanlife/findadoc-server/pull/218 <- You are here
1. Added a `getSubmission` function to `submissionService.ts`.
2. Added a `submission` query to `resolvers.ts`.
3. Added a `SubmissionFilters` input to schema.
4. Added a `SubmissionFilters` type alias to `dbSchema.ts` to define the data types for each field.
1. Run the development server using `yarn dev`.
2. Open your browser and navigate to http://localhost:3001 to access the GraphQL Studio.
5. In the GraphQL Studio, click the …
=> feat: Add getSubmission function

.all-contributorsrc, README.md
Adds Anissa to our list of contributors! 🥳
=> docs: add anissa to contributors

README.md, package.json
Prior to this commit some devs were experiencing problems with the seeds not appearing in the emulator. This adds instructions to the README to solve this problem.
Resolves #246
=> docs: update instructions for emulator

src/resolvers.ts, src/services/submissionService.ts
Previously, submissions with empty fields were accepted and added to the database. This ensures that all required fields (googleMapsUrl, healthcareProfessionalName, and spokenLanguages) are provided.
Resolves #261 
1. Added validation to ensure` googleMapsUrl` and `healthcareProfessionalName` are not empty.
2. Validated `spokenLanguages` and ensured it's not an empty array.
Copy and paste this into the GraphQL Studio:
**Operation:**
```
mutation Mutation($input: SubmissionInput) {
createSubmission(input: $input) {
id
}
}
```
**Variables:**
```
{
"input": {
"googleMapsUrl": " ",
"healthcareProfessionalName": "Dr Bob",
"spokenLanguages": [
{
"iso639_3": "eng",
"nameJa": "English",
"nameEn": "English",
"nameNative": "English"
}
]
}
}
```
You should receive an error similar to this:
```
{ …
```
=> Require all fields for addSubmission function

src/services/submissionService.ts
Previously, when adding a submission, the `id` was not being saved to the `id` field. With some minor changes, it now saves to the `id` field.
Resolves #281
- Used `submissionRef.id` to generate a new id.
- Passed the generated ID to the convertToDbSubmission function.
- Used the `set` method to overwrite the document in the 'submissions' collection with the generated ID.
- Changed the id assignment in `convertToDbSubmission` from an empty string to `submission.id`.
1. Run the following mutation in GraphQL Studio:
```
mutation Mutation($input: SubmissionInput) {
createSubmission(input: $input) {
id
}
}
```
2. Use the following variables:
```
{
"input": {
"googleMapsUrl": "https://maps.google.com/clinicA",
"healthcareProfessionalName": "Dr. Phil",
"spokenLanguages": [
{
"iso639_3": "Eng", …
```
=> addSubmission method now saves an ID to the database

src/resolvers.ts, src/result.ts, src/services/facilityService.ts, src/services/healthcareProfessionalService.ts, src/services/submissionService.ts, src/typeDefs/dbSchema.ts, src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
When a moderator flags a user submission as approved, a new facility and/or healthcare professionals will be created.
Resolves #220 
Resolves #318
Resolves #296 
**NOTE: tests were split into #323, facility<-->provider relationship updates were split into #324** 
1. Added a conditional statement to `updateSubmission` to check is the submission has been marked as `approved`. If so, the `addFacility` and `addHealthcareProfessional` service functions are called.
2. Added a new table to schema called `UpdateSubmissionInput` in order to separate user inputs from moderator inputs.
- NOTE: this logic has not been tested yet to work. This will come later in #323. 
- For now, let's just validate the app still runs. Ensure `yarn dev` works and tests pass
=> Create `approveSubmission` function and logic

__tests__/healthcareProfessional.test.ts, src/fakeData/fakeHealthcareProfessionals.ts, src/services/healthcareProfessionalService.ts, src/validation/validationHealthcareProfessional.ts
Resolves #357 
1. Add more validation requirements to degrees in HP.
2. Move validation logic for degrees to validation folder, under validationHealthcareProfessional file.
3. Refactor degrees field for nameJa in fakeHealthcareProfessionals.
4. Writing test for degrees and names validations.
5. Refactor some validations of names (because of testing I notice some mistakes or improvements)
=> Build out validation for degrees field of HP

package.json
fixing production deploy issue
=> fixing pm2 cloud issue

src/server.ts
changed the healthcheck url to be the root path for digitalocean to find
=> updating healthcheck url

package.json, tsconfig.json, yarn.lock
Change the command to run the dev server to resolve ts-node error.
=> refactor: change cmd to run dev server

src/server.ts
Set the fastify host to `0.0.0.0`
=> refactor: set fastify host

src/services/facilityService.ts, src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
This enables us to grab facilities that are related to professionals.
=> added facility filtering by professional ids

src/resolvers.ts, src/services/healthcareProfessionalService.ts, src/validation/validationHealthcareProfessional.ts
Resolves #277 
Created search professionals resolver, service, and validation!
=> created search professionals resolver, service

package.json
fixing prod issue.
removing package.json entry
=> removing the packagemanager entry

package.json
=> fixing build script bug

.env.dev, .env.prod, src/server.ts, utils/environmentVariables.ts
=> host is now an env variable

src/resolvers.ts
removed auth from createsubmission
=> removed auth from createsubmission

src/server.ts
allowing localhost calls to api
=> allowing localhost calls to api

src/server.ts
allowing localhost calls to api 2
=> allowing localhost calls to api2

src/services/submissionService.ts, src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
=> chore: add notes to schemas

src/server.ts
enable netlify previews to use api
=> enable netlify previews to use api

src/server.ts
Add 'https://www.findadoc.jp' to the cors origin list.
=> add main domain to cors origin

src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
Add unsinsured to insurance enum
=> Add unsinsured to insurance enum

package-lock.json, src/services/submissionService.ts, src/validation/validateSubmissions.ts
Part of #339 
Added validation for createSubmissions that:
- Prevents creating submissions with empty string for `healthcareProfessionalName`, `googleMapsUrl`.
- Prevents creating submissions with special characters numbers for `healthcareProfessionalName`.
- Limits `healthcareProfessionalName` to 128 characters and `googleMapsUrl` to 1028 characters.
- Prevents the use of `<script>` tags in `healthcareProfessionalName`, `googleMapsUrl`.
- Requires at least one spoken language in the `spokenLanguages` array.
Run the mutation:
```
mutation Mutation($input: CreateSubmissionInput!) {
createSubmission(input: $input) {
id
googleMapsUrl
healthcareProfessionalName
spokenLanguages
createdDate
}
}
```
And the variables:
```
{
"input": {
"googleMapsUrl": "https://maps.google.com/exampleA", …
```
=> Validate Create Submission Inputs

.env.prod
Updates the URLS for the API and Website in the production environment file.
=> fix: point the prod env to correct urls

__tests__/testSetup.test.ts, src/server.ts
Resolves #412 
- fixing prod url to not have the `/api`
=> fixing urls

src/server.ts
Resolves #446 
- fixed route in fastify blocking deploy previews
see if a netlify deploy preview can load data
=> BUG: fixing deploy previews cors issue

src/services/healthcareProfessionalService.ts
Resolves #531 
Added a filter to search professionals by name.
-Add testing.
=> feat: add names filter to searchProfessionals

src/resolvers.ts, src/services/auditLogService.ts, src/services/submissionService.ts, src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
Resolves #276 
- Add audit trailing when submission is created
- Add audit trailing when submission is deleted
- Add audit trailing when submission is updated
-  Create tests for audit trailing
=> feat: add audit trailing to submissions

src/services/facilityService.ts, src/services/healthcareProfessionalService.ts
Resolves #641 
Before due to some variable names and update order the backend was incorrectly updating the relationships of both the healthcare professional with the facility and the facility relationship to remove the id of the HP. It is now correctly updating both the HP and Facility with the changes.
=> fix: refactor healthcare facility relationship to properly update database

.husky/pre-push, __tests__/auth.test.ts, src/auth.ts
Resolves #768 
Tests added for auth
`yarn test`
=> feat(test): implement tests for auth

src/auth.ts
- Fixed the permissions to remove the roles after all the roles have been added
=> fix: fixed auth permission issue for dev role access

src/services/submissionService.ts
Resolves #792 
A conditional was added so we can accept partially a new submission healthcare professional we have with existing facility or vice versa
You can still on the frontend in local environment approve a whole submission
=> refactor: update logic to handle submissions to just be facility or hp

src/services/submissionService.ts
Resolves #801 
fixed bug i introduced
manually tested
=> fix: fix submission bug

src/typeDefs/gqlTypes.ts, src/typeDefs/schema.graphql
Resolves #[874]
Addition of OD - Doctor of Optometry to `healthcareProfessionals` schema
Also re-arranged the options to be in alphabetical order.
1. `yarn generate` to update the schema
2. Create a healthcare professional with assigned degree of OD
=> feat: add OD to degrees schema
