package.json
src/typesgeneratorconfig.ts
yarn.lock

There was a plugin missing in the `typesgeneratorconfig.ts` that was preventing all of the necessary types from being generated. This fix will allow us to change all of the types that are set to `any` to their appropriate types.
1. Delete the `src/typeDefs/gqlTypes.ts` file and run the following:
```
yarn dev
yarn generate
```
2. Check that the generated file includes the `export type` and `export enum` that are missing from `main`.

fix codegen to add missing types

---

.eslintrc.js
README.md
package.json
prisma/devSetup.ts
prisma/migrations/20230109085948_spoken_languages/migration.sql
prisma/schema.prisma
prisma/seed.ts
src/db/client.ts
src/mockData/mockData.ts
src/resolvers.ts
src/services/spokenLanguageService.ts
src/typeDefs/schema.graphql
yarn.lock

Part of #87 and resolves #45
Run the following in Apollo Sandbox:
```
query Query {
spokenLanguages {
iso639_3
nameEn
nameJa
nativeName
}
}
```
Run the backend then click the following to fill the query
https://studio.apollographql.com/sandbox/explorer?endpoint=http%3A%2F%2Flocalhost%3A3001%2F&explorerURLState=N4IgzghgbgpgJgYQPYBsUwMYBcCWSB2AknCAFwgwQBGcGA7DDALQBsEAHAGZMAsdEzKuwCszAAwAmKgGYe0sTwh0JEkABpw0eMjSZcBAKL4sAJwCexMiACM9aROlUWTKhjjte1uh44SAnEzs7BCy0hgS7HCc0iAAvkA&referrer=operation_collections
Test cases for iso code: 'spa' should retrieve spanish, 'eng' english, 'xxx' null

Connect DB and GraphQL in spoken languages

---

README.md
docker-compose.yml
docker/db-init.sh
prisma/schema.prisma

Resolves #90 
1. Adds `platform: linux/amd64` to the Docker build.
2. Updates the README steps for getting the database running
1. Follow the updated steps in the README to get the database and docker running.
2. Do the following query in GraphQL studio:
Operation:
```
query Query($iso6393: String!) {
spokenLanguage(iso639_3: $iso6393) {
nameNative
nameJa
nameEn
iso639_3
}
}
```
Variables
```
{
"iso6393": "eng"
}
```

fix: set platform version to make prisma compatible with M1

---

prisma/devSetup.ts

Resolves #94 
- Ensure the seed file can be run more than once without getting ugly constraint errors and crashing the script
You should be able to run `docker compose up` multiple times in a row (not in parallel) without deleting the docker container. The containers should shut down gracefully like so:
```sh
...
findadoc-server-migrate-1       |   id: 13,
findadoc-server-migrate-1       |   nameJa: '何',
findadoc-server-migrate-1       |   nameEn: 'Physician Assistant / Associate',
findadoc-server-migrate-1       |   abbreviation: 'PA'
findadoc-server-migrate-1       | }
findadoc-server-migrate-1       | { id: 5, nameJa: '医師', nameEn: 'Medical Doctor', abbreviation: 'MD' }
findadoc-server-migrate-1       |
findadoc-server-migrate-1       | 🌱  The seed command has been executed. …
```

avoid DB conflicts

---

.editorconfig
package.json
prisma/schema.prisma
tsconfig.json

Resolves #58 
- Add editor config 
- Update indentation style to be 4 as much as possible
(we can adjust the graphql and yaml files later but I am worried about merge conflicts right now
EditorConfig works automatically with many tools: https://editorconfig.org/#pre-installed
If you have VS Code, you will need to install a plugin: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
Now when you edit files, you should automatically get the right indentation when you press tab, have the correct line endings `\n` (unix) not `CRLF` (windows). It can help us easily work with folks on different platforms. 
Thanks to @ermish for suggesting it

add editor config and adjust indentation to 4

---

prisma/devSetup.ts
prisma/seed.ts

Resolves #121 
Changes the `forEach` in the seed functions to for loops, because we discovered a race condition in #116.
1. Run `docker compose up`
2. Run `yarn prisma studio`
3. Confirm that the seeds in Prisma Studio match those found in `specialties.csv` and `spokenLanguages.csv`

fix: replace forEach to fix race condition

---

package.json

Resolves #[Issue number]
Not sure if will work but I'm attempting to fix the builds with the following script (set in digitalocean):
```shell
npm install --production=false && npm run build && rm -rf node_modules && yarn install && cp src/typeDefs/schema.graphql dist/src/typeDefs/.
```
I was trying to invoke the typescript compiler directly but I think we may have to run it through npm for it to work. This script essentially installs dev dependencies, runs the typescript compiler, removes the node_modules directory and reinstalls to ensure only the production dependencies are installed. Then it moves the schema file which is not added to the generated application. The run step of the app has been updated to run `node dist/src/index.js`. This seems to work locally so I am hoping it works …

test build commands

---

.gitignore
README.md
package-lock.json
package.json
src/database.ts
yarn.lock

Prior to this change, a new developer starting server would get an error message saying private key is missing. Installed `dotenv` to handle environment variables in the code. Updated `README` with instructions on how to get a private key from firebase and how to add it to the local `env` file.
Resolves #198
1. Added `dotenv package` to load environment variables into `process.env`.
2. Added `firebaseServiceAccountKey.json` to `gitignore` to keep `private_key` private.
3. Removed unused imports from `database.ts`.
4. Changed `credentials` variable to point to `firebaseServiceAccountKey.json`.
5. Added instructions to `README` for setting up Firebase Service Account.
1. Run `yarn install` to update dependencies.
2. Make sure to have a private key file generated by Google Firestore.
3. Add …

fix: add firebase service account key to env variable

---

src/typeDefs/schema.graphql

The reason for this change is to allow users to submit incomplete information to be reviewed by moderators prior to being searchable on the website
Resolves #202 
1. Added a `type` called `Submission` and an `input` called `SubmissionInput`.
2. Added `submissions` and `submission` to `type Query`.
1. Run `yarn dev` and navigate to `localhost:3001` to open the Apollo Server Playground.
3. In the left pane under Query, click the `+` next to `submission`, then `id: ID!`.
4. In the middle pane, under Variables, replace the value of `"submissionId": null` with an id, i.e. `"1"`, then click the blue Submission button.
5. A Status 200 in the right pane means the query for a single submission was a success.
6. To query for all submissions, click Query in the left pane, then click the `+` next to …

feat: add Submission type and input

---

.github/CODEOWNERS

Temporarily removing CODEOWNERS, because it's placing a burden on development with a team so small on a private repository.

Remove codeowners until the repo goes public

---

src/resolvers.ts
src/services/submissionService.ts
src/typeDefs/dbSchema.ts
src/typeDefs/schema.graphql

Previously there were no service functions to allow users to get, add, or update submissions. There are now functions to perform these tasks. There is now also a Submission type alias in `TypeDefs/dbschema.ts`.
Part of #212 
This PR is part of a 🥞:
1. https://github.com/ourjapanlife/findadoc-server/pull/213 <- You are here
2. https://github.com/ourjapanlife/findadoc-server/pull/218 
1. Added a type alias called `Submission` to `dbSchema.ts` to define the data types for each field.
3. Created a file in `src/services` called `submissionService.ts` to house the submission-related functions.
4. Added three main functions: 
- **`getSubmissionById`**: Retrieves a specific submission by its ID.
- **`addSubmission`**: Adds a new submission.
- **`updateSubmission`** : Updates an existing …

feat: add a submissionService file and Submission type definitions

---

src/errors.ts

Previous to this commit in the errors file, missingInput was missing an underscore what made the error codes not consistent. In this commit I have added a underscore.
Resolves #247

feat: make error code consistent

---

__tests__/server.test.ts
src/services/healthcareProfessionalService.ts

Previously, the test only passed if the error message matched the tested sentence exactly. To make a more dynamic I refactor the way we test the error message.
Resolves #262 
Refactor the tests for the error path, focusing more on the error message. Add a spyOn mock function to verify if Customerrors.notFound() has been called. Also, test the error message by checking if it is defined and has a length greater than 0, rather than a specific message.

Refactor the error message tests

---

src/index.ts
src/resolvers.ts

Previously, resolvers were missing try and catch blocks and this caused undesired behavior when making a query or mutation request when they missed required values/fields.
Resolves #255 
1. Added try and catch blocks to all resolvers
2. Added the custom errors in the catch block
If you would make a mutation, example create submission, without an id as followed, it will throw an error now:
```mutation Mutation($input: SubmissionInput) {
createSubmission(input: $input) {
googleMapsUrl
healthcareProfessionalName
spokenLanguages {
iso639_3
nameEn
nameJa
nameNative
}
}
}
```

Add error messages/handeling to resolvers

---

package.json

Previously the project name was left out in the dev:startlocaldb script and this prevented the seeding from happening for certain developers
Resolves #279

Add project name to dev:startlocaldb script

---

__tests__/server.test.ts
src/services/healthcareProfessionalService.ts

Previously try and catch blocks and error messaging where missing from healthcareProfessionalService. To make error handling more consistent I added try and catch blocks and error messages.
Resolves #253 
Add try and catch blocks and error messages to the healthcareProfessionalService.

Add error handling to healthcareprofessionalService

---

__tests__/submissionService.test.ts
src/services/submissionService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql
tsconfig.json

Part of #249 
Resolves #287 
1. Implements a test for addSubmission that sends a request through Apollo Server and checks the response against expected values. This is the first step to adding tests using real inputs instead of mock data, schema, and/or server.
2. Removes `isApproved` from SubmissionInput. The reasoning is because the value defaults to false when a new Submission is created, and shouldn't be a required field when a user completes the Submission form.
3. Changes `isUnderReview` from `true` to `false` so moderators will be able to know which Submission are being actively reviewed, and which are still in the backlog.
1. Start Firestore emulator through Docker by running: `yarn test:dockerstart`
2. Run the tests using `yarn test` or just the new test file using `yarn test -- …

test: add E2E test for newSubmission

---

__tests__/facilities.test.ts
src/resolvers.ts
src/services/facilityService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #294 
This PR is part of a 🥞
1. https://github.com/ourjapanlife/findadoc-server/pull/292
2. https://github.com/ourjapanlife/findadoc-server/pull/293 👈🏼 You are here
1. Creates the `updateFacility` mutation
4. Makes the `ContactInput` fields optional
5. Adds happy path test for `updateFacility`
1. Run `yarn test:dockerstart` to start the Docker container
3. Run `yarn test` and make sure all of the tests pass
4. Run `yarn dev` to start the local server
6. Create a new Facility in GraphQL Studio and copy the ID
7. Use the `updateFacility` mutation and make sure to pass the ID in the Variables. Example:
```json
{
"updateFacilityId": "yu1KvHOKeb8npvdtwBsc",
"input": {
"nameEn": "some other facility name",
"isDeleted": true,
"contact": {
"email": "happyhappy@happy.com"
}
},
}
```

feat: implement updateFacility

---

__tests__/submissions.test.ts
src/resolvers.ts
src/services/submissionService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #280 
1. Updates the schema and gqlTypes for  `SubmissionInput`
2. Refactors `getSubmissionById` to return a `<Result<Submission>>`
3. Refactors `updateSubmission` so it uses `doc.set()` instead of `doc.update()`. The reason is because `doc.set()` allows us to pass `{merge: true}` which tells Firestore to merge the changes into the existing data instead of replacing it all. ([documentation](https://firebase.google.com/docs/firestore/manage-data/add-data))
4. Adds test for the happy path for `updateSubmission`
1. Run `yarn test:dockerstart` to start the Docker container
2. Run `yarn test` and ensure the tests pass
3. Run `yarn dev` and create a new Submission and copy the ID
4.  Use the ID to update the Submission. Example:
**Operation:**
```gql
mutation …
```

fix: allow for partial updates of submissions

---

src/resolvers.ts

Resolves #298 
Previously there were spelling error in the error messages in the Resolver file, I have corrected the typos.

fix: replace spelling typo 'where' with 'were'

---

__tests__/submissions.test.ts
package.json
src/services/submissionService.ts
yarn.lock

Resolves #301 
1. Add happy path test for searchSubmission method.
2. Add tests for the different filters.
3. Add docstrings to the searchSubmission method.
4. Add test environment for the firestore emulator. After every test the emulator will now clear the data.
1. Add error path for searchSubmission
2. Add test enviroments to server.tests and facilities.test.

Add happy path test for searchSubmission method

---

.eslintrc.js

Quick commit to ignore the max length rule for strings, urls, comments, and non-code related lines. 
We live in a world above 720p resolution monitors ✨

update max length to ignore strings and comments

---

__tests__/facilities.test.ts
__tests__/healthcareProfessional.test.ts
src/index.ts
src/resolvers.ts
src/result.ts
src/services/facilityService.ts
src/services/healthcareProfessionalService.ts

Resolves #312
Resolves #316 
Resolves #317 
- run `yarn test` and validate all tests are passing
- run `yarn dev` and send a query that has invalid variables. 
Ex. search facilities and send `limit: -1` as a filter. You should see the new formatted errors
``` json
query QueryFacilities($filters: FacilitySearchFilters) {
facilities(filters: $filters) {
id
contact {
address {
addressLine1En
addressLine2En
addressLine1Ja
cityJa
cityEn
}
email
mapsLink
phone
website
}
isDeleted
nameEn
nameJa
healthcareProfessionalIds
}
}
```
``` json
variables
{
"filters": {
"limit": -1,
"offset": 1,
"nameEn": "Zoo"
}
}
```

Set up result.errors to gqlerror converter

---

renovate.json

This PR reverses the change that I to set the confidence level to high for the renovate bot updates. It hasn't opened any PRs to update the packages since then, and I suspect that the setting was either incorrectly implemented, or was set too high.  😅

chore: revert renovate bot back to previous confidence level

---

package.json

Change `copyfiles` to `copyfiles -a` to include files that start with a dot.

refactor: add -a option to copyfiles

---

package.json

Removes the single quotes to the copyfiles cmd since [the docs](https://www.npmjs.com/package/copyfiles) shows them as not needed.

refactore: remove single quotes from copyfiles

---

package.json

Adds the `--no-daemon` flag to pm2 so it runs in the foreground.

refactor: add no-daemon flag to pm2

---

__tests__/submissions.test.ts
src/services/healthcareProfessionalService.ts
src/services/submissionService.ts

Due to a firebase limitation, professionals search can only query by one array-based field. The rest of them need to be done in the  code after the query is done. This adds the logic.
...also fixed tests that someone broke  (not me 😆 )

enhanced professionals search

---

.env.prod
src/auth.ts

Resolves #412
- updated the api url to no longer be `/api`, but use the subdomain `api.findadoc.jp`

updated api url

---

src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Previously we had placeholder email addresses in our database that we did not want to display in our `SearchResultDetails` component. This PR updates the GraphQL schema to to make facility email addresses nullable.
Part of #436 
Remove non-nullable operator `!` from GraphQL `Contact` type and `ContactInput`.
Run `npm run dev`, navigate to `http://127.0.0.1:4000/`, and run the following mutation:
**Operation**
```
mutation Mutation($input: CreateFacilityInput!) {
createFacility(input: $input) {
id
nameEn
contact {
email
}
createdDate
updatedDate
}
}
```
**Variables**
```
{
"input": {
"contact": {
"address": {
"addressLine1En": "test",
"addressLine1Ja": "テスト",
"addressLine2En": "5555-55 test",
"addressLine2Ja": "テスト5555-55",
"cityEn": "test",
"cityJa": "テスト",
"postalCode": "123-0000", …
```

fix: Make facility email field nullable

---

README.md
package.json

No issue linked due to no view for backend
The readMe was a bit outdated and therefore I could see new people coming in trying to run the dummy data in the local database have trouble setting it up. I went through and updated the language that was there and added instructions for two parts of Java that need to be installed. I also commented out the husky command. There is no script for it. Whether there should be or not it would just be a stumbling block for people who do not know why they are getting the error or might now be familiar with how we are implementing husky and linting
You can follow step by step to see if it makes sense to you

chore: update readMe to be more comprehensive

---

utils/databaseSeedTool.ts

Resolves: #467 
The the fake submissions data was missing from the seeding file, therefore we did not have any seeded data for submissions
- Add the fake data to the seeding file
Run `npm run dev:startlocaldb`
Then `npm run dev`
Visit emulator database and see the seeded data for submissions. 
This is a quick fix, so we can work on the frontend. This means I didn't check in depth that fake data is as it should be.

Add fake submissions data to seeding file

---

package.json

Resolves #469 
After we migrated from Yarn to npm, the lint command did not work. It showed an error that it not recognize `ESLINT_USE_FLAT_CONFIG` variable. 
- Add cross-env to the command
- I have also removed the `fix` tag, the reason is that people (including me) forget to commit those linting changes. With the fix gone your linting will fail when it catches an error, and you will be more consciously about fixing those errors.
I did not add cross-env to the `lint:ci` since that command is running fine in our ci.
Please checkout this branch and run `npm run lint` command.

BUG: Debug npm run lint command

---

__tests__/facilities.test.ts
src/typeDefs/gqlTypes.ts

Resolves https://github.com/ourjapanlife/findadoc-server/issues/482
-Before the facility submissions didn't have the map coordinate type so we couldn't autofill on the frontend with the types generated on the frontend by the schema on the backend. I added two tests for the query of submissions to make sure that the coordinates appeared as expected
You can go to the branch and run the tests with:
```
npm run test
```

chore: add tests and types for coordinates

---

src/typeDefs/schema.graphql

I added the coordinates to the types on the backend in #482 . This one adds the types to the schema which is what generates the types for the frontend. Thanks to @Anissa3005 For explaining to me that the `schema.graphql` file is what needs to be changed
Run the server with:
```
npm generate 
```
And see if the type for the floats of the coordinates is part of the `FacilitySubmission` type.

chore: add coordinates to schema `FacilitySubmission`

---

README.md

Resolves #520 
- Under the title **Run the API** I have replaced the `npm run dev:startserver` command with `npm run dev`
- Added extra information how to run the API and what the command does
- Removed unnecessary title from the setting up the database

docs: replace the run API command with the correct one in the README

---

utils/databaseSeedTool.ts

Resolves #555 
Since we made recently changes to the frontend, it's better to use the partial data again since that represents real case scenarios.
Besides that, with adding audit trailing this would add unnecessary audit logs.
I have remove the `updateSubmissions` from `seedingDatabase`.

Refactor: remove updateSubmissions from seedingDatabase

---

src/services/submissionService.ts

Resolves #566 
Before it just set a submission to `isApproved` but also should set `isUnderReview` to false if it has been approved.

fix: implement isUnderReview boolean change

---

__tests__/submissions.test.ts
src/services/submissionService.ts

Resolves #570 
Before the function for `approveSubmission` had the order wrong on what needed to be created when approving a facility. Now a facility is created...and then the healthcare professionals if they need to be. Then finally the submission is changed to `isApproved` This is so that the correct order of logic exists. Also before there was a bug that we never set the data of the request to the `Submission`. Now this is set properly so we can send back the request to the frontend. All the steps should happen in this order or it should not be approved since some some error occurred in the approval process.
A test was added to test the functionality of this functionality based on this logic order.
1.  Submission is created
2. Submission is updated to `isUnderReview`
3. Submission is …

fix: reorder logic of creation of submission

---

src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #587 
There was an assumption that the user can accurately report languages. So on a new Healthcare Professional submission it is good to have this type shown as unspecified until the moderator has the chance to confirm.

chore(lang): add unspecified language choice

---

src/services/auditLogService.ts
src/services/submissionService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql
utils/submissionDataFromGoogleMaps.ts

Resolves #640 
The `createAuditLog` function required refactoring because its parameter types were too restrictive, limiting its usage to adding submissions. By changing the parameters to accept string types, the function can now be implemented more flexibly across different use cases.
Additionally, I updated the GraphQL schema to make the newData field optional. This is necessary for delete operations, where the newData field needs to be set to null.
1. Refactored the createAuditLog function to use string types for its parameters.
2. Updated the GraphQL schema to make the newData field optional.
3. Fixed an import bug in submissionDataFromGoogleMaps, this bug made it impossible to run the server.

refactor: change the parameter types for createAuditLog

---

src/services/healthcareProfessionalService.ts

Resolves #644
Previously, updating a healthcare professional required all fields to be provided. If any fields were missing, it caused validation errors.
This PR adds conditionals to the validation logic, allowing updates to one or more specific fields. For example, you can now update only the name field without providing other fields.
1. Add conditionals to the `validateUpdateProfessionalInput` function.

fix: add conditionals to allow updating specific fields

---

__tests__/auditTrail.test.ts

Previously, there was a bug in the createAuditLog test caused by the newAuditLog argument having the wrong data type. This PR fixes the issue by updating the newAuditLog argument to the correct data type, string.
1. Updated the newAuditLog argument data type to string in the createAuditLog test.

fix: update data type of newAuditLog  argument in createAuditLog test

---

src/resolvers.ts
src/services/facilityService.ts
src/services/healthcareProfessionalService.ts
src/services/submissionService.ts
utils/databaseSeedTool.ts

Resolves ##274
This PR adds audit trailing to the facility service actions: create, update, and delete. It also includes some refactoring to improve functionality and address related issues, such as converting batch writes to transactions.
1. Added audit trailing to the following actions: 
-  `createFacility`
-   `updateFacility`
-   `deleteFacility`
2. Fixed a missing parameter in the approveSubmission logic when calling the createFacility function.
3. Refactored updateHealthcareProfessionalsWithFacilityIdChanges to use transactions instead of batch writes.

feat: add audit trailing to facility service actions create, update and delete

---

package.json

Digital ocean App Platform is not properly picking up our yarn version, so the build is failing. This should be a fix for it.

BUG: Adding fix for digitalocean build

---

package.json

This removes Yarn from the `packageManager` field in package.json. We were advised by Digital Ocean support to follow this [documentation from Heroku](https://help.heroku.com/8MEL050H/why-is-my-node-js-build-failing-because-of-no-matching-yarn-versions) in order to use Yarn v4+. This should also resolve build warnings we were seeing relating to having Yarn specified in two different fields:
```
2025-01-15T15:47:20.708414293Z [34m│[0m ! Multiple Yarn versions declared
2025-01-15T15:47:20.708559560Z [34m│[0m
2025-01-15T15:47:20.708748617Z [34m│[0m The package.json file indicates the target version of Yarn to install in two fields:
2025-01-15T15:47:20.708901361Z [34m│[0m - "packageManager": "[yarn@4.6.0](mailto:yarn@4.6.0)"
2025-01-15T15:47:20.709042956Z [34m│[0m - "engines.yarn": …
```

fix: remove yarn from packageManager field

---

.github/pull_request_template.md
.github/workflows/lint-pr-title.yml

Adds the same PR title validation that we have on the front end to check for [conventional commits ](https://www.conventionalcommits.org/en/v1.0.0/)formatting.

feat: add workflow for validating pr titles

---

README.md

Resolves #738
The links in the `README` were updated to the correct urls for the second and third link
This is previous. If you loo at the changes I updated the links to have the correct slugs for the `Quickstart the API` and `Run the API`
[📒 Welcome to Find a Doc, Japan!](https://documentation.findadoc.jp/development)
[🚅 Quickstart the API](https://app.gitbook.com/o/Hmir5Cugknp7uJaXBpz1/s/8SwzLo8dTmkYT8nK5WXz/start-coding/quickstart-the-frontend-and-backend)
[🚀 Run the API](https://app.gitbook.com/o/Hmir5Cugknp7uJaXBpz1/s/8SwzLo8dTmkYT8nK5WXz/start-coding/quickstart-the-frontend-and-backend/running-the-api-locally)
Click the links in the read me and it shouldn't ask you to log in

fix: change urls in README to consistent slug for gitbook

---

src/server.ts

Resolves #779 
Before our cors had a wildcard domain for . This does not work with fastify and `CORS` because the `*` wildcard only works when credentials is false.
This uses a function that takes a callback that returns true or false whether the origin is allowed by checking an array without the flag and a match with regex to match our deployment preview URLS

feat: implement updated CORS for frontend deploy previews

---

src/server.ts

Casted string as TS needs the origin to check and if there isn't an origin it is calling itself or bash. But we do not need that functionality.

fix: fix typescript error with typecasting

---

src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

This updates our schema to have the second address line be optional since it is not necessary to have one if they do not have secondary information such as floor number or office number

fix: change address secondary to be optional

---

__tests__/healthcareProfessional.test.ts
__tests__/healthcareProfessionalValidations.test.ts
src/fakeData/fakeHealthcareProfessionals.ts
src/services/healthcareProfessionalService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #802
Added an `additionalInfoForPatients` field to hp schema so that we can display additional information that clinics want patients to know about. It's an optional field that by default will be an empty string
Try starting the local db and local server and see if you can see the new field in the fake hp data (it should be there as empty strings). You can also test the update by trying to send an update request to make a new string for the additionalInfoForPatients field

refactor: add additionalInfoForPatients field to hp

---

src/services/healthcareProfessionalService.ts

Resolves #[Issue number]
Before we casted the type as a string. This would cause it to try to add undefined as the value to the key in firestore which is not allowed. So now we set it to an empty string if undefined. This logic works for firestore and our frontend as we only display notes if it is truthy

fix: update mapping to set additional info to empty string instead of undefined

---

__tests__/auth.test.ts
src/auth.ts
src/resolvers.ts

The auth in our backend did not match our store which disallowed generic users to create submissions in prod

fix: change permission scope for creating submission

---

src/auth.ts

This now keeps create for the user as well. This was missed in manual testing due to the conditional using production

fix: update permission function

---

src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Mongolian was not a choice in our Locales and through moderation we have come across healthcare professionals who speak this language

chore: add mongolian to Locale enum

---

src/resolvers.ts

Previously we were thinking the authorize function allows if any scope is allowed. But it is if you need a combination of scopes in the array to allow. So this adds a conditional that checks for two different scopes

fix: update isAuthorized to use conditional due to functionality

---

package.json
yarn.lock

You can now run `yarn dev` instead of having to run `yarn:startlocaldb` and `yarn:startserver` separately! 
I tried concurrently before, but it broke because of the interactive prompts needed. Figured out you can use `--raw` to fix this. 
Make sure `yarn:dev` works for you now

feat: figure out how to run the two tasks together

---

__tests__/user.test.ts

Resolves #897 
- created a new file `user.test.ts` in the directory `__tests__`
- the test runs a mutation request to create a user and search query to get the newly created user by it's id. Then it compares the original input values and the searched values to make sure they are the same 
run the tests locally to see if it passes and the user tests show up in the tests running

feat: create tests for createUser and getUserById

---

__tests__/auth.test.ts
src/auth.ts
src/resolvers.ts
src/services/reservationService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #895 
- added the following to `schema.graphql` and `gqlTypes.ts` :
type `Reservation`, enum `ReservationStatus`, input `CreateReservationInput`, input `UpdateReservationInput`
reservation query, createReservation mutation, updateReservation mutation
-  added the following resolvers
reservation query resolver, createReservation mutation resolver
- added `reservationService.ts` to handle resolvers
- added the following new Scopes to auth.ts and put under each Role for now
`read:reservations` , `write:reservations` 
- updated auth.test.ts to include `read:reservations` and `write:reservations`
- try to create a User with the backend
- then, try to create a reservation using a user id
- if you use an existing user id, should successfully create a reservation
- if not an existing …

feat: create new reservation table, reserverationService, graphql resolvers, and domain model

---

src/resolvers.ts
src/services/userService.ts
src/typeDefs/gqlTypes.ts
src/typeDefs/schema.graphql

Resolves #907 
- added `updateUser`, `updateUserInput` to `schema.graphql` and `gqlTypes.ts`
- added `updateUser` resolvers to `resolvers.ts`
- added an `updateUser` function to `userService.ts` that handles the logic for carrying out the update (currently still using the in memory array data base)
- start apollo server and create a user
- try to update the user with a new display name and/or new profile pic url

feat: create update user mutation
